// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyHelper.Data;

namespace MyHelper.Migrations
{
    [DbContext(typeof(ProgramContext))]
    [Migration("20250210083727_AddDirectoryTableNickname2")]
    partial class AddDirectoryTableNickname2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.32");

            modelBuilder.Entity("MyHelper.Models.Entity.ColomnEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DirectoryColomnName")
                        .HasColumnType("TEXT")
                        .HasMaxLength(70);

                    b.Property<string>("DirectoryTableKey")
                        .HasColumnType("TEXT")
                        .HasMaxLength(70);

                    b.Property<string>("DirectoryTableName")
                        .HasColumnType("TEXT")
                        .HasMaxLength(70);

                    b.Property<string>("DirectoryTableNickname")
                        .HasColumnType("TEXT")
                        .HasMaxLength(70);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsEqualsRecordStar")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsQuotes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT")
                        .HasMaxLength(70);

                    b.Property<string>("Records")
                        .HasColumnType("TEXT");

                    b.Property<int>("Sort")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TableId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TableId");

                    b.ToTable("Colomns");
                });

            modelBuilder.Entity("MyHelper.Models.Entity.SettingEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .HasColumnType("TEXT")
                        .HasMaxLength(70);

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Settings");
                });

            modelBuilder.Entity("MyHelper.Models.Entity.TableDirectoryEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("TabkeKey")
                        .HasColumnType("TEXT")
                        .HasMaxLength(70);

                    b.Property<string>("Table")
                        .HasColumnType("TEXT")
                        .HasMaxLength(70);

                    b.Property<string>("TableNickname")
                        .HasColumnType("TEXT")
                        .HasMaxLength(70);

                    b.Property<string>("rf_Colomn")
                        .HasColumnType("TEXT")
                        .HasMaxLength(70);

                    b.Property<string>("rf_Table")
                        .HasColumnType("TEXT")
                        .HasMaxLength(70);

                    b.HasKey("Id");

                    b.ToTable("TableDirectories");
                });

            modelBuilder.Entity("MyHelper.Models.Entity.TableEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .HasMaxLength(200);

                    b.Property<string>("Guid")
                        .HasColumnType("TEXT")
                        .HasMaxLength(70);

                    b.Property<string>("IsCreateSubFolder")
                        .HasColumnType("TEXT")
                        .HasMaxLength(1);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IsOpenFile")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsTemplateScript")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT")
                        .HasMaxLength(70);

                    b.Property<string>("Number")
                        .HasColumnType("TEXT")
                        .HasMaxLength(3);

                    b.Property<string>("Path")
                        .HasColumnType("TEXT");

                    b.Property<string>("Project")
                        .HasColumnType("TEXT")
                        .HasMaxLength(70);

                    b.Property<int>("Sort")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Sprint")
                        .HasColumnType("TEXT")
                        .HasMaxLength(10);

                    b.Property<string>("Task")
                        .HasColumnType("TEXT")
                        .HasMaxLength(20);

                    b.HasKey("Id");

                    b.ToTable("Tables");
                });

            modelBuilder.Entity("MyHelper.Models.Entity.ColomnEntity", b =>
                {
                    b.HasOne("MyHelper.Models.Entity.TableEntity", "Table")
                        .WithMany("Colomns")
                        .HasForeignKey("TableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
